import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/components/ui/header";
import { Provider } from "@/components/ui/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Book Club",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <main className="font-mono mx-auto container">
            <Header />
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
