import { Geist_Mono } from "next/font/google";
import "./globals.css";

import { ApolloWrapper } from "@/components/apollo-wrapper";
import Header from "@/components/ui/header";
import { Provider } from "@/components/ui/provider";
import { CurrentUserProvider } from "@/context/CurrentUserContext";

const geistMono = Geist_Mono({
  subsets: ["latin"],
});

export const metadata = {
  title: "Book Club",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistMono.className} antialiased`}
        style={{ height: "auto", minHeight: "calc(100vh - 30px)" }}
      >
        <ApolloWrapper>
          <CurrentUserProvider>
            <Provider>
              <main className="mx-auto container">
                <Header />
                {children}
              </main>
            </Provider>
          </CurrentUserProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
